language: c
sudo: required
cache:
  directories:
    - /var/cache/apt/
    - /var/cache/pbuilder/aptcache/

matrix:
  include:

   # ###### Ubuntu Linux ####################################################

   # ====== Ubuntu 20.04 (Focal Fossa) ======================================
   - name: "Ubuntu 20.04 (Focal Fossa) with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:focal" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Ubuntu 20.04 (Focal Fossa) with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:focal" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 20.04 (Focal Fossa) packaging with pbuilder"
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:focal" VARIANT="ubuntu" TOOL="pbuilder"

   # ====== Ubuntu 20.10 (Groovy Gorilla) ======================================
   - name: "Ubuntu 20.10 (Groovy Gorilla) with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:groovy" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   #- name: "Ubuntu 20.10 (Groovy Gorilla) with Clang"
     #os: linux
     #dist: focal
     #group: travis_latest
     #env: DOCKER="ubuntu:groovy" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 20.10 (Groovy Gorilla) packaging with pbuilder"
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:groovy" VARIANT="ubuntu" TOOL="pbuilder"

   # ====== Ubuntu 18.04 (Bionic Beaver) ====================================
   - name: "Ubuntu 18.04 (Bionic Beaver) with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   #- name: "Ubuntu 18.04 (Bionic Beaver) with Clang"
     #os: linux
     #dist: focal
     #group: travis_latest
     #env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 18.04 (Bionic Beaver) packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="pbuilder"

   # ====== Ubuntu 16.04 (Xenial Xerus) =====================================
   - name: "Ubuntu 16.04 (Xenial Xerus) with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   #- name: "Ubuntu 16.04 (Xenial Xerus) with Clang"
     #os: linux
     #dist: focal
     #group: travis_latest
     #env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 16.04 (Xenial Xerus) packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="pbuilder"


    # ###### Debian Linux ###################################################

    # ====== Debian Testing =================================================
   - name: "Debian Testing with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:testing" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   #- name: "Debian Testing with Clang"
     #os: linux
     #dist: focal
     #group: travis_latest
     #env: DOCKER="debian:testing" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Debian Testing packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:testing" VARIANT="debian" TOOL="pbuilder"

   # ====== Debian Sid ======================================================
   - name: "Debian Sid with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:sid" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   #- name: "Debian Sid with Clang"
     #os: linux
     #dist: focal
     #group: travis_latest
     #env: DOCKER="debian:sid" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Debian Sid packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:sid" VARIANT="debian" TOOL="pbuilder"

   # ====== Debian Buster ===================================================
   - name: "Debian Buster with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:buster" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   #- name: "Debian Buster with Clang"
     #os: linux
     #dist: focal
     #group: travis_latest
     #env: DOCKER="debian:buster" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Debian Buster packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:buster" VARIANT="debian" TOOL="pbuilder"

   # ====== Debian Stretch ==================================================
   - name: "Debian Stretch with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:stretch" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   #- name: "Debian Stretch with Clang"
     #os: linux
     #dist: focal
     #group: travis_latest
     #env: DOCKER="debian:stretch" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Debian Stretch packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:stretch" VARIANT="debian" TOOL="pbuilder"


   # ###### Fedora Linux ###################################################

   # ====== Fedora 33 =======================================================
   - name: "Fedora 33 with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="fedora:33" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   #- name: "Fedora 33 with Clang"
     #os: linux
     #dist: focal
     #group: travis_latest
     #env: DOCKER="fedora:33" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Fedora 33 packaging with mock"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="fedora:33" VARIANT="fedora" TOOL="mock"

   # ====== Fedora 32 =======================================================
   - name: "Fedora 32 with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="fedora:32" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   #- name: "Fedora 32 with Clang"
     #os: linux
     #dist: focal
     #group: travis_latest
     #env: DOCKER="fedora:32" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Fedora 32 packaging with mock"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="fedora:32" VARIANT="fedora" TOOL="mock"

   # ====== Fedora Rawhide ==================================================
   # - name: "Fedora Rawhide with GCC"
   #   os: linux
   #   dist: focal
   #   group: travis_latest
   #   env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   # - name: "Fedora Rawhide with Clang"
   #   os: linux
   #   dist: focal
   #   group: travis_latest
   #   env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   # - name: "Fedora Rawhide packaging with mock"
   #   os: linux
   #   dist: focal
   #   group: travis_latest
   #   env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="mock"


   # ###### Other ###########################################################

   # ====== MacOS X ========================================================
   # - name: "MacOS X"
   #   os: osx
   #   osx_image: xcode9.4
   #   compiler: clang
   #   group: travis_latest


before_install:
  - ci/before-install

install:
  - ci/install

script:
  - ci/build
  - |
    if [ "${VARIANT}" != "debian" ] ; then   # There is no Debian PPA for the required rsplib-* packages!
       ci/test
    fi
